version: '3.9'

services:
  api:
    container_name: api
    build: .
    ports:
      - 3001:3001
    environment:
      - DB_HOST=db
      - DB_PASSWORD=1234
      - DB=WebContact
      - DB_USER=ggabr
      - SECRET_KEY=1234
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=ggabr
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=WebContact
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ggabr -d WebContact"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s